version: '3.8'

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/conf.d/default.prod.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend
      - realtime
      - frontend
    networks:
      - ticketing-network
      - nginx-proxy
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-ticketing}
      MYSQL_USER: ${DB_USERNAME:-ticketuser}
      MYSQL_PASSWORD: ${DB_PASSWORD:-ticketpass}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-rootpass}
    networks:
      - ticketing-network

  redis:
    image: redis:7.0-alpine
    command: [ "redis-server", "--notify-keyspace-events", "Ex" ]
    networks:
      - ticketing-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env
    environment:
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      REDIS_HOST: redis
      REDIS_CLIENT: phpredis
      JWT_SECRET: RBFyraVNL1Ovmwm8jtcO4sMnTB4RzTJpis3s6Q0MCjPQ9ScSlYdjNCko2zaz9tNo
    # En producció NO hi ha volums de codi
    depends_on:
      - mysql
      - redis
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/api/events" ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 30s
    networks:
      - ticketing-network

  realtime:
    build:
      context: ./realtime
      dockerfile: Dockerfile
    environment:
      REDIS_HOST: redis
      JWT_SECRET: RBFyraVNL1Ovmwm8jtcO4sMnTB4RzTJpis3s6Q0MCjPQ9ScSlYdjNCko2zaz9tNo
    deploy:
      replicas: 3 # Alta disponibilitat real
    depends_on:
      - redis
    networks:
      - ticketing-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod # Fa servir la versió compilada amb Nginx
    networks:
      - ticketing-network

networks:
  ticketing-network:
    driver: bridge
  nginx-proxy:
    external: true
